### ISSUE TITLE
Speedup initialization of charset AutoDetectReader required for language detection

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/nutch#7]
Most time required for charset detection is spent to initialize the AutoDetectReader and to load the list of EncodingDetectors from jar/job file. It should be possible to speed this up.
![warc_writer_charset_detection_prof](https://user-images.githubusercontent.com/1630582/60349417-da32a200-99c1-11e9-957c-0920ee6157a9.png)

**Comment by tfmorris** [comment]
Since the list of detectors is static, you should be able to cache it. You could try using [this constructor](https://tika.apache.org/1.20/api/org/apache/tika/detect/AutoDetectReader.html#AutoDetectReader-java.io.InputStream-org.apache.tika.metadata.Metadata-org.apache.tika.config.ServiceLoader-) to pass in a ServiceLoader. There's also a [private constructor](https://github.com/apache/tika/blob/5eec28ae0203820364dbcdef58335fd64aeb90ec/tika-core/src/main/java/org/apache/tika/detect/AutoDetectReader.java#L104) which takes a list of detectors directly, avoiding all lookup overhead (although I suspect that the class loader caching will do what you need if you just reuse the ServiceLoader.

p.s. Since cloned repos aren't searchable on Github (annoying!) here's the relevant source file: [LanguageDetector.java](https://github.com/commoncrawl/nutch/blob/cc/src/java/org/commoncrawl/util/LanguageDetector.java)

**Comment by sebastian-nagel** [comment]
Thanks, @tfmorris. Yes, I could overwrite the ServiceLoader and cache the list of classes implementing EncodingDetector. Looks like I have to instantiate them every call because detectors may be stateful. Actually, it's a [known issue in Tika (TIKA-1568)](https://issues.apache.org/jira/browse/TIKA-1568)), I'll first try to get it solved there.

**Comment by sebastian-nagel** [comment]
For a detailed analysis, please check the [interactive SVG.zip](https://github.com/commoncrawl/nutch/files/3339651/fetcher.reduce.28673.async-prof.svg.zip).

**Comment by tfmorris** [comment]
Getting the Tika folks to fix it would definitely be my first choice! Even if you had to re-instantiate them, I think you'd be way ahead because the bulk of the time is going to [ServiceLoader.identifyStaticServiceProviders()](https://github.com/apache/tika/blob/master/tika-core/src/main/java/org/apache/tika/config/ServiceLoader.java#L318) and that list is never going to change so all those repeated JAR file lookups are just a waste. Class loading and instantiation is a minuscule fraction of the time.

**Comment by tballison** [comment]
Which version of Tika are you using?  How are you constructing your parsers?

We've been caching encoding detectors if you do a single call to, e.g., `new AutoDetectParser()` and then use that throughout.  When each parser that extends AbstractEncodingDetectorParser is created, the encoding detector is created for that parser and then reused on every 

There's every chance that I'm misunderstanding our code. :D

**Comment by tballison** [comment]
Done (almost)!

https://issues.apache.org/jira/browse/TIKA-1568?focusedCommentId=16883215&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16883215

**Comment by tballison** [comment]
Sorry for the idiocy, but can you tell me what profiler you used to get the image above?

**Comment by tfmorris** [comment]
The profile is referenced in one Sebastian's other performance issues. It is [async-profiler](https://github.com/jvm-profiling-tools/async-profiler).

**Comment by tballison** [comment]
@tfmorris Thank you!

**Comment by sebastian-nagel** [comment]
Hi @tballison, in case it is still relevant: Tika 1.20 was used and here [the call of AutoDetectReader](https://github.com/commoncrawl/nutch/blob/04ae437f62a8d3307d5998e7f241ac9291623c4b/src/java/org/commoncrawl/util/LanguageDetector.java#L106). I'll try your fix tomorrow. Thanks!
Async-profiler is great: small footprint (one jar file, one shared object and a shell script), only the PID is required, no Java options at startup of the profiled process, profiles both Java and native code. The limitations: Unix only (Linux, MacOS) and (usually) root privileges are required to enable the [perf events](https://en.wikipedia.org/wiki/Perf_(Linux)).

**Comment by sebastian-nagel** [comment]
Solution confirmed, see [TIKA-1568](https://issues.apache.org/jira/browse/TIKA-1568?focusedCommentId=16883720). I'll use the Tika 1.22-SNAPSHOT jars for now (not committed because this requires to carefully test everything after each build), the issue will be finally fixed when the Tika dependencies are upgraded to 1.22.

**Comment by sebastian-nagel** [comment]
Profiler screenshot after the fix of TIKA-1568:
![Screenshot_20190712_133122](https://user-images.githubusercontent.com/1630582/61125196-77ed9d00-a4a9-11e9-913a-67d5d5c65f9c.png)
